// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ3EXbK7pC7CdhYN6gYFMS7VubbA_Klrc',
    appId: '1:731071297707:web:33a040a023b61ab22c5fee',
    messagingSenderId: '731071297707',
    projectId: 'internship-app-1',
    authDomain: 'internship-app-1.firebaseapp.com',
    storageBucket: 'internship-app-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIyDjtYv7MUElZO1SIOFxAZypcH9fyvno',
    appId: '1:731071297707:android:120bbcd5e78223222c5fee',
    messagingSenderId: '731071297707',
    projectId: 'internship-app-1',
    storageBucket: 'internship-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJjJ0V0W703cz5v-UbTFnvkpEGz1SjI8',
    appId: '1:731071297707:ios:a8952a8b0e4a95cd2c5fee',
    messagingSenderId: '731071297707',
    projectId: 'internship-app-1',
    storageBucket: 'internship-app-1.firebasestorage.app',
    iosBundleId: 'com.example.internshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJjJ0V0W703cz5v-UbTFnvkpEGz1SjI8',
    appId: '1:731071297707:ios:a8952a8b0e4a95cd2c5fee',
    messagingSenderId: '731071297707',
    projectId: 'internship-app-1',
    storageBucket: 'internship-app-1.firebasestorage.app',
    iosBundleId: 'com.example.internshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ3EXbK7pC7CdhYN6gYFMS7VubbA_Klrc',
    appId: '1:731071297707:web:1d5ed64cdec290832c5fee',
    messagingSenderId: '731071297707',
    projectId: 'internship-app-1',
    authDomain: 'internship-app-1.firebaseapp.com',
    storageBucket: 'internship-app-1.firebasestorage.app',
  );

}